### ISSUE TITLE
Would you share the datasets for your project?

### ISSUE THREAD

**Issue by NamhyeokKim** [previtus/ChangeDetectionProject#1]
I have a big interest in your project.
So, I want to reproduce it. Would you share the datasets?

**Comment by previtus** [comment]
Hello,
Glad that you are interested in the project :).

The dataset sadly isn't available publicly, it comes from the Swiss company Swisstopo. More exactly, it consists of images recorded over a 303 km2 region of Aarau (recorded in maps as area No. 1089 in 25 cm resolution) in years of 2012 and 2015. 
This company offers similar type of data as it's "[SWISSIMAGE_RS](https://shop.swisstopo.admin.ch/en/products/images/ortho_images/SWISSIMAGE_RS)" product (as raw as possible data, with 4 bands - NearInfra,R,G,B - where we were using only the RGB channels).

However I am not sure if these exact datasets from years 2012 and 2015 are up on their websites. And I am quite sure that the annotation is not up there.
_(Btw: I know how difficult it is to find this sort of high quality data publicly, so I am sorry that I can't share it.)_
