### ISSUE TITLE
Dataset and a pre-trained model (您好，数据是什么，可以共享吗？有没有预训练模型呢？)

### ISSUE THREAD

**Issue by ghost** [previtus/ChangeDetectionProject#2]

**Comment by previtus** [comment]
Hello,
I roughly translated your questions as _"Hello, what is data, can it be shared? Is there a pre-trained model?"_

There is a demo with a **pre-trained model** here: https://github.com/previtus/ChangeDetectionProject/blob/master/demo/_ChangeDetection_prediction_example.ipynb

And please check details about the **dataset** here: https://github.com/previtus/ChangeDetectionProject/issues/1 (basically these datasets are sadly private but probably could be obtained from the Swiss company Swisstopo)

**Comment by ghost** [comment]
谢谢，这个需要在 Google colab上运行，我还在研究

**Comment by previtus** [comment]
Hello, yes, please **run it directly with**: https://colab.research.google.com/github/previtus/ChangeDetectionProject/blob/master/demo/_ChangeDetection_prediction_example.ipynb and don't forget to change the **runtime to GPU**. It will need you to **login to Google** as well due to downloading the pre-trained model.

**Comment by ghost** [comment]
> 您好，是的，请**直接通过**以下[网址](https://colab.research.google.com/github/previtus/ChangeDetectionProject/blob/master/demo/_ChangeDetection_prediction_example.ipynb)**运行它**：[https](https://colab.research.google.com/github/previtus/ChangeDetectionProject/blob/master/demo/_ChangeDetection_prediction_example.ipynb) : [//colab.research.google.com/github/previtus/ChangeDetectionProject/blob/master/demo/_ChangeDetection_prediction_example.ipynb](https://colab.research.google.com/github/previtus/ChangeDetectionProject/blob/master/demo/_ChangeDetection_prediction_example.ipynb)，不要忘记将**运行时**更改**为GPU**。由于下载了预先训练的模型，它也需要您**登录Google**。

Thank you very much!
