### ISSUE TITLE
Dataset demo

### ISSUE THREAD

**Issue by gsndr** [previtus/ChangeDetectionProject#3]
Hi,
I tried to run your code, in particular the activelearningloop.py file. Where I can find the datasets used for experiments.
For example I have this error /scratch/ruzicka/python_projects_large/ChangeDetectionProject_files/saved_paths_2012_256x256_cleanManualALL.pickle
but I don't found the pickle file in the repository

**Comment by gsndr** [comment]
As an alternative, can you help me to explain the running of ActiveLearningLoop.py? How the code must be run in order to work with a custom dataset?

**Comment by previtus** [comment]
Hello,
Which parts are you trying to use or reimplement - the Active Learning or the ML model?

Sadly the dataset is not publicly available. A brief description of the **AL loop** is in the paper (link: https://arxiv.org/abs/2008.11201 in "3 Method" or in the accompanying slides: https://previtus.github.io/data/presentation_DeepActiveLearningForChangeDetection_MACLEAN2020.pdf).

Alternatively there's an extracted version of the Siamese U-Net **model** here: https://github.com/previtus/ChangeDetectionProject/blob/master/Model2_builder.py
(Uncomment the bit at the bottom and use "segmentation-models" version 0.2.0)

I am not planning rewriting the AL code for a different dataset as of yet, but I have used the model with the Onera Change Detection dataset (in a non Active Learning setting) - there is a code demo here which can be ran on Google Colab: https://github.com/previtus/change_detection_onera_baselines or directly: [https://colab.research.google.com/github/previtus/change_detection_onera_baselines/blob/main/_colabs/1f_oneraCD_rgb_SiameseUnet.ipynb](https://colab.research.google.com/github/previtus/change_detection_onera_baselines/blob/main/_colabs/1f_oneraCD_rgb_SiameseUnet.ipynb?authuser=0)

**Comment by gsndr** [comment]
Thanks I solved
